name: callme
on:
  workflow_call:
    inputs:
      hellostring:
        description: Say hello
        required: false
        type: string

jobs:
  hello:
    name: hello1
    runs-on: ubuntu-latest

    steps:
    - name: say-hi
      run: |
        echo "HELLO1"
    
    - name: print-input
      if: "${{ inputs.hellostring == 'hello' }}"
      run: |
        echo "${{ inputs.hellostring }}"
