name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install http-server
      - name: Start server
        run: npx http-server -p 8080
        env:
          CI: true
      - name: Print URL
        run: echo "Server running at http://localhost:8080"
