name: Build erlang with FIPS (pro)
on:
  workflow_dispatch:

###
#  Build erlang with FIPS enabled
#  We have to build erlang from source to enable FIPS. The default APT pkg is not compiled with it.

#  This action is based on xDome similar process and the following:
#  https://github.com/rabbitmq/erlang-debian-package/blob/OTP-26.x/ubuntu/22.04/.github/workflows/test-ubuntu-jammy.yaml

#  Docs:
#  https://github.com/openssl/openssl/blob/master/INSTALL.md
#  https://github.com/openssl/openssl/blob/master/README-FIPS.md
#  https://docs.openssl.org/master/man7/fips_module
#  https://www.erlang.org/doc/apps/crypto/fips.html
#  https://github.com/erlang/otp/blob/OTP-26.2.5.4/HOWTO/INSTALL.md

###

env:
  ERLANG_TAG_VERSION: OTP-26.2.5.4
  ERLANG_DEBIAN_PACKAGE_TAG_VERSION: OTP-26.x/ubuntu/22.04
  ERLANG_DEBIAN_PACKAGE_COMMIT: 3fbf92ec309069f737eb1f3fb9e610531a931274 # Commit of version $ERLANG_TAG_VERSION in erlang-debian-package repo
jobs:
  build-erlang:
    container:
      image: ubuntu:jammy
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            ca-certificates git wget \
            make g++ pkg-config ncurses-dev gcc libssl-dev 

      - name: Enable ubuntu-pro
        run: |
          export DEBIAN_FRONTEND="noninteractive"

          apt-get install -y --no-install-recommends ubuntu-advantage-tools

          pro attach ${{ secrets.UBUNTU_PRO_TOKEN }}

      - name: Install openssl-fips
        run: |
          pro enable fips-updates --assume-yes

          apt-get install openssl-fips-module-3
          openssl fipsinstall -out /usr/lib/ssl/fipsmodule.cnf -module /usr/lib/x86_64-linux-gnu/ossl-modules-3/fips.so

          # Config fips to be used by default
          # https://docs.openssl.org/master/man7/fips_module/#making-all-applications-use-the-fips-module-by-default
          export OPENSSL_CNF="/usr/lib/ssl/openssl.cnf"
          export FIPSMODULE_CNF="/usr/lib/ssl/fipsmodule.cnf"

          sed -i "/^\[openssl_init\]/i\\.include ${FIPSMODULE_CNF}\n" "$OPENSSL_CNF"
          sed -i '/^providers = provider_sect/a\alg_section = algorithm_sect' "$OPENSSL_CNF"
          sed -i 's/^\(default = default_sect\)/# \1/' "$OPENSSL_CNF"
          sed -i 's/^# fips = fips_sect/fips = fips_sect/' "$OPENSSL_CNF"
          sed -i '/^fips = fips_sect/a\base = base_sect' "$OPENSSL_CNF"
          sed -i '/^base = base_sect/a\\n[base_sect]\nactivate = 1\n\n[algorithm_sect]\ndefault_properties = fips=yes' "$OPENSSL_CNF"

          # Verify that fips is enabled
          openssl list -providers

      - name: Build erlang
        id: build
        run: |
          set -eux

          export DEBIAN_FRONTEND="noninteractive"

          # Install build tools
          apt-get install -y build-essential devscripts equivs gnupg rsync git-buildpackage
                    
          # This was supposed to be in action/checkout@v4 but the action doesn't init .git
          git clone --depth 1 --branch ${{ env.ERLANG_TAG_VERSION }} https://github.com/medigateio/erlang-otp
          git clone --branch ${{ env.ERLANG_DEBIAN_PACKAGE_TAG_VERSION }} https://github.com/medigateio/rabbitmq-erlang-debian-package

          # Checkout specific commit to be aligned with the otp version
          cd rabbitmq-erlang-debian-package
          git checkout $ERLANG_DEBIAN_PACKAGE_COMMIT
          cd ..

          dist_version=debian-$(cat /etc/debian_version)
          cp -a rabbitmq-erlang-debian-package/debian erlang-otp/
          cd erlang-otp/

          branch=rabbitmq-erlang-debian-package-by-rabbitmq
          git checkout -b "$branch"

          # Configure git-buildpackage
          cat > ~/.gbp.conf <<EOF
          [DEFAULT]
          upstream-tag = $ERLANG_TAG_VERSION
          EOF

          # Remove non-free documentation
          for fn in $(find lib/*/doc -name standard -or -name archive); do
              rm -rf "$fn"
          done

          # Build package
          mk-build-deps -i -t 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y'
          rm -f erlang-build-deps*

          # We add here `--enable-fips` to the configure command so that Erlang will be compiled with it
          sed -i -E 's/(\s+)--prefix=/\1--enable-fips --prefix=/' debian/rules

          gbp buildpackage \
            --git-ignore-new \
            --git-debian-branch="$branch" \
            --no-sign | tee /tmp/erlang-build.logs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: erlang-fips-artifacts
          path: |
            erlang-*.deb
            erlang-*.ddeb
            erlang_*.dsc
            erlang*build*
          if-no-files-found: error
          retention-days: 60
