name: Hello World

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print file
        run: cat hello-world.txt
