name: Slack alert

on:
  workflow_call:
    inputs:
      header_text:
        required: true
        type: string
      # TODO: sensitive
      # slack_webhook_url:
      #   required: true
      #   type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get time upon failure
        id: time
        uses: josStorer/get-current-time@v2
        with:
          timezone: "Israel"
          format: 'HH:mm:ss | DD/MM/YYYY'

      - name: Send slack notification
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: "${{ secrets.slack_webhook_url }}"
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ inputs.header_text }}",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Ran by:*\n${{ github.triggering_actor }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\n${{ steps.time.outputs.formattedTime }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "Open"
                      },
                      "style": "danger",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
