name: Trigger slack alert
on:
  workflow_dispatch:
    inputs:
      repo:
        description: param
        required: true
        type: string

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  fail-on-purpose:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: |
          exit 1
        
  slack:
    if: ${{ failure() }}
    uses: ./.github/workflows/slack-alert.yml
    with:
      repo: ${{ inputs.repo }}
    secrets:
      slack_webhook_url: ${{ secrets.VERY_IMPORTANT_SECRET }}
