name: trigger callme
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  hello2:
    name: hello2
    runs-on: ubuntu-latest

    steps:
    - name: say-hi
      run: |
        echo "HELLO2"
  
  trigger-if-release-branch:
    uses: ./.github/workflows/callme.yml
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: hello2

  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: wait 30
        run: |
          sleep 30

  fail-on-purpose:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: |
          exit 1
  
  run-on-depends:
    uses: ./.github/workflows/callme.yml
    if: ${{ always() }} 
    needs: [ trigger-if-release-branch, sleep, fail-on-purpose ]
    with:
      hellostring: "hello"