name: trigger callme
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  hello2:
    name: hello2
    runs-on: ubuntu-latest

    steps:
    - name: say-hi
      run: |
        echo "HELLO2"
  
  trigger-if-release-branch:
    uses: ./.github/workflows/callme.yml
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: hello2

  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: wait 10
        run: |
          sleep 10

  fail-on-purpose:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: |
          exit 1

      - name: Get time upon failure
        if: ${{ failure() }}
        id: time
        uses: josStorer/get-current-time@v2
        with:
          timezone: "Israel"
          format: 'HH:mm:ss | DD/MM/YYYY'
    
      - name: Send slack upon failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RD_MEDSTREAM_BUILD_ERROR_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Build medstream failed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Ran by:*\n${{ github.triggering_actor }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\n${{ steps.time.outputs.formattedTime }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "Open"
                      },
                      "style": "danger",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
    
          
  run-on-depends:
    if: always() && !contains(needs.*.result, 'failure')
    needs: [ trigger-if-release-branch, sleep, fail-on-purpose ]
    # needs: [ trigger-if-release-branch, sleep]
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          echo "toJSON(needs) = ${{ toJSON(needs) }}"
          echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"
          echo "!contains(needs.*.result, 'skipped') = ${{ !contains(needs.*.result, 'skipped') }}"
          echo "!contains(needs.*.result, 'failure') = ${{ !contains(needs.*.result, 'failure') }}"
