name: trigger callme
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  hello2:
    name: hello2
    runs-on: ubuntu-latest

    steps:
    - name: say-hi
      run: |
        echo "HELLO2"
  
  trigger-if-release-branch:
    uses: ./.github/workflows/callme.yml
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: hello2

  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: wait 10
        run: |
          sleep 10

  # fail-on-purpose:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: fail
  #       run: |
  #         exit 1
  
  # Fail -> should not run
  run-on-depends:
    uses: ./.github/workflows/callme.yml
    if: always() && !contains(needs.*.result, 'failure')
    # needs: [ trigger-if-release-branch, sleep, fail-on-purpose ]
    needs: [ trigger-if-release-branch, sleep]
    with:
      hellostring: "hello"

  debug-print:
    needs: [run-on-depends]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "toJSON(needs) = ${{ toJSON(needs) }}"
          echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"
          echo "!contains(needs.*.result, 'skipped') = ${{ !contains(needs.*.result, 'skipped') }}"
          echo "!contains(needs.*.result, 'failure') = ${{ !contains(needs.*.result, 'failure') }}"