name: Trigger slack alert
on:
  workflow_dispatch:
    inputs:
      repo:
        description: param
        required: true
        type: string

jobs:
  fail-on-purpose:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: |
          exit 1
        
  slack:
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    needs: [fail-on-purpose]
    uses: ./.github/workflows/slack-alert.yml
    with:
      header_text: TEST ${{ inputs.repo }}
    secrets:
      slack_webhook_url: ${{ secrets.RD_XDOME_DOCKER_BUILD_ERRORS_SLACK_WEBHOOK_URL }}
