name: trigger callme
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  hello2:
    name: hello2
    runs-on: ubuntu-latest

    steps:
    - name: say-hi
      run: |
        echo "HELLO2"
  
  trigger:
    uses: ./.github/workflows/callme.yml
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: hello2

  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: wait 30
        run: |
          sleep 30
  
  triggerhello:
    uses: ./.github/workflows/callme.yml
    # Run even if one skipped
    if: ${{ always() }} 
    needs: [ trigger, sleep ]
    with:
      hellostring: "hello"