name: trigger trigger callme
on:
  workflow_dispatch:
  push:
    branches:
      - release/*

jobs:
  hello3:
    name: hello3
    runs-on: ubuntu-latest

    steps:
    - name: say-hi
      run: |
        echo "HELLO3"
  
  trigger-release:
    if: contains('refs/heads/release', github.ref)
    uses: ./.github/workflows/trigger-callme.yml
    needs: hello3
  
  trigger-master:
    if: contains('refs/heads/master', github.ref)
    uses: ./.github/workflows/trigger-callme.yml
    needs: hello3
